name: Bug Report min
description: Create a report with a procedure for reproducing the bug
title: "BUG: "
labels: [bug]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.
      render: markdown
